// ==UserScript==
// @name         Google sheet - WBGS utility
// @namespace    GS_WBGS_Reader
// @version      0.1
// @description  Utility for google sheet for WBGS.
// @include      https://docs.google.com/spreadsheets/*
// @grant        GM.setClipboard
// @grant        GM.registerMenuCommand
// ==/UserScript==


(async function() {
	//This script simply searches for any sheets in the google sheet file that is generated by WBGS, assuming you have started a process with "Save results in a new Sheet" option checked.
	//This then lets you copy a list of the sheet names into your clipboard via the menu command of the userscript (e.g. greasemonkey, violentmonkey), without having to manually
	//right-click, rename, and copy the name individually.
	
	//This script is intended along with having the "Save results in a new Sheet" option checked, and a process duplication bug* occurs, to quickly obtain the timestamps of when each
	//of the processes started traversing** URLs. This is then can be used to report this process duplication bug to WBGS.
	
	//*A bug on WBGS that you start a process, it queues, then later emails you that a process have begun and starts saving URLs (as usual), but then later, emails you and another process
	// started again with identical process tracking URL.
	//**I use the term "traverse" to refer to when it actually starts saving URLs, it does not include the time when it says "Job queued and waiting for free worker to begin".

	//From what I experienced, when you start a process and it queues, then starts saving URLs, the date displayed on the home screen of WBGS shows the UTC date and time of when
	//it starts queuing, not when it starts traversing URLs.
	//
	//When a process starts traversing, it creates a new sheet, with a name being a UTC date and time of when it starts traversing URLs rather than the start of the queue.
	//If the process duplicates, the WBGS homepage list of process will list each duplicates along with the original, all being identical, and on the google sheet file used in the process,
	//multiple new sheets will spawn each having their own UTC date and time rather than all being the same UTC.
	
	//Settings
		const Setting_ScanRate = 1000 //Interval delay in milliseconds. Code execute periodically to reflect changes
		const Setting_TimestampSortDescend = false //false = from earliest to latest, true = opposite
	//Don't touch unless you know what you're doing
		let String_WBGSNewSheetList = ""
	
	//Code below
		let ScanInterval = setInterval(GetSheetTabTimestamp, Setting_ScanRate)
		
		function GetSheetTabTimestamp() {
			//Get sheets tab at bottom of screen, and obtain their names
				let ElementContainingSheetTabs = document.querySelector("div.docs-sheet-container-bar.goog-toolbar.goog-inline-block")
				if (ElementContainingSheetTabs == null) {
					return
				}
				let SheetTabs = [...ElementContainingSheetTabs.childNodes] //Get list of sheets
				let SheetTabs_WBGS_SaveResultInNewSheet = SheetTabs.filter(tab => /^\d+-\d+-\d+ \d+:\d+ UTC/.test(tab.textContent)) //Get only tabs generated by WBGS
				if (SheetTabs_WBGS_SaveResultInNewSheet.length ==0 ) { //If none are found
					return
				}
				
				let TimestampList = SheetTabs_WBGS_SaveResultInNewSheet.map(tab => {
					let TabNameElement = tab.querySelector("span")
					if (TabNameElement != null) {
						return {
							Timestamp: TabNameElement.textContent,
							TimeMS: new Date(TabNameElement.textContent).valueOf()
						}
					}
					return "error"
				})
				
				let OrderLabel = ""
				if (!Setting_TimestampSortDescend) {
					OrderLabel = "earliest to latest"
					TimestampList.sort((a,b) => a.TimeMS-b.TimeMS)
				} else {
					OrderLabel = "latest to earliest"
					TimestampList.sort((a,b) => b.TimeMS-a.TimeMS)
				}
				
				String_WBGSNewSheetList = "" //Reset the string just in case
				
				String_WBGSNewSheetList += "Timestamp list, ordered from " + OrderLabel + ":\n"
				TimestampList.forEach((item, index, arr) => {
					String_WBGSNewSheetList += item.Timestamp
					if (index != arr.length-1) {
						String_WBGSNewSheetList += "\n"
					}
				})
		}
		GM.registerMenuCommand("Copy WBGS result sheets", CopyWBGSSheets, "");
		function CopyWBGSSheets() {
			GM.setClipboard(String_WBGSNewSheetList)
		}
})();